# Numpy basics

In [7]:
import numpy as np

In [8]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [3, 5, 1]])
a.shape
print(len(a))
print(len(a[1]))
print(a[:2])

print(a[0][1])
print(a[2][2])
print(a[1:])
print(a[1:][1])
print(a[1:][1][1])

3
3
[[1 2 3]
 [4 5 6]]
2
1
[[4 5 6]
 [3 5 1]]
[3 5 1]
5


In [9]:
for i in range(len(a)):
    for j in range(len(a[i])):
        print("element", a[i][j])

element 1
element 2
element 3
element 4
element 5
element 6
element 3
element 5
element 1


In [15]:
b = [[1,2],[1,4],[2,4]]
b = np.array(b)
#b.append([1,9])
b

array([[1, 2],
       [1, 4],
       [2, 4]])

In [11]:
a[1,1]

5

In [14]:
b[1,1]

4

In [18]:
b.ndim



2

In [19]:
a.ndim

2

In [29]:
c = np.array([[[2,3,4],[3,5,9],[0,3,4]],[[2,3,4],[3,5,9],[0,3,4]],[[2,3,4],[3,5,9],[0,3,4]]])

In [30]:
c.ndim

3

In [37]:
import math
c.size == math.prod(a.shape)
print(math.prod(a.shape))
print(c[0])


9
[[2 3 4]
 [3 5 9]
 [0 3 4]]


# Array of Zeros

In [64]:
arr = np.array(([np.zeros(3)],[np.ones(3)],[np.zeros(3)]))
arr

array([[[0., 0., 0.]],

       [[1., 1., 1.]],

       [[0., 0., 0.]]])

In [53]:
arr[1]

array([[1., 1., 1.]])

In [54]:
arr.dtype

dtype('float64')

In [80]:
arr1 = np.array([[[1., 2., 3.],[4, 5., 6.],[7, 8., 9.]],
                [[11., 12., 13.],[14, 15., 16.],[17, 18., 19.]],
                [[21., 22., 23.],[24, 25., 26.],[27, 28., 29.]]])
arr1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [94]:
arr1.shape

(3, 3, 3)

In [84]:
new = []
for i in range(len(arr1)):
    for j in range(len(arr1[i])):
        for k in range(len(arr1[j])):
            print(f'element number {i}*{j}*{k}: ', arr1[i,j,k])
            new.append(arr1[i,j,k])

print(new)

element number 0*0*0:  1.0
element number 0*0*1:  2.0
element number 0*0*2:  3.0
element number 0*1*0:  4.0
element number 0*1*1:  5.0
element number 0*1*2:  6.0
element number 0*2*0:  7.0
element number 0*2*1:  8.0
element number 0*2*2:  9.0
element number 1*0*0:  11.0
element number 1*0*1:  12.0
element number 1*0*2:  13.0
element number 1*1*0:  14.0
element number 1*1*1:  15.0
element number 1*1*2:  16.0
element number 1*2*0:  17.0
element number 1*2*1:  18.0
element number 1*2*2:  19.0
element number 2*0*0:  21.0
element number 2*0*1:  22.0
element number 2*0*2:  23.0
element number 2*1*0:  24.0
element number 2*1*1:  25.0
element number 2*1*2:  26.0
element number 2*2*0:  27.0
element number 2*2*1:  28.0
element number 2*2*2:  29.0
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0]


In [85]:
arr.shape

(3, 1, 3)

In [99]:
n = np.array(new)

In [104]:
n = n.reshape(3,3,3)

In [105]:
print(n.reshape(3,3,3))

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[11. 12. 13.]
  [14. 15. 16.]
  [17. 18. 19.]]

 [[21. 22. 23.]
  [24. 25. 26.]
  [27. 28. 29.]]]


In [106]:
n.ndim
#new.ndim

3

In [107]:
n

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]],

       [[21., 22., 23.],
        [24., 25., 26.],
        [27., 28., 29.]]])

In [108]:
n1 = n[np.newaxis,:]
n1.shape

(1, 3, 3, 3)

In [110]:
n2 = n1[np.newaxis,:]
n2.shape

(1, 1, 3, 3, 3)

In [118]:
n2[0][0][2]

array([[21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.]])

In [119]:
aa = np.array(['adi','ad',2,2.4])
aa.nbytes

512

In [120]:
a= 3
b=1
print(a,b)
a,b = b,a
print('*'*20)
print(a,b)

3 1
********************
1 3


# Pandas


In [121]:
import numpy as np
import pandas as pd

In [123]:
s = pd.Series([1,3,5,7,5])
s

0    1
1    3
2    5
3    7
4    5
dtype: int64

In [124]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [126]:
s = pd.Series([1,3,5,7,5], index=['a','b','c','d','e'])
s

a    1
b    3
c    5
d    7
e    5
dtype: int64

In [128]:
s[0:5:2]

a    1
c    5
e    5
dtype: int64

In [132]:
s[['a','c']]

a    1
c    5
dtype: int64

In [137]:
s[s>3]

c    5
d    7
e    5
dtype: int64

In [141]:
df = pd.DataFrame([[1,3,5,7,5]],[[11,13,15,17,15]]) #,columns=['chan','mat'])
df

0  1  2  3  4
11  1  3  5  7  5
13  1  3  5  7  5
15  1  3  5  7  5
17  1  3  5  7  5
15  1  3  5  7  5