## Coding Exercise #0102

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3

array([3, 6, 9])

In [7]:
b + b

array([2, 4, 6])

In [8]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
a-b

array([-3, -3, -3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [14]:
x = np.array([0, 1, 2, 3, 4, 5])

In [15]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [16]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [17]:
type(np.sqrt)

numpy.ufunc

In [18]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [19]:
np.random.seed(123)
a = np.random.randint(1, 11, size=1000)

In [20]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.median(a)

5.0

In [22]:
np.sum(a)

5485

In [23]:
np.round(np.var(a),2)

8.19

In [24]:
np.round(np.mean(a),2)

5.48

In [25]:
np.round(np.std(a),2)

2.86

In [26]:
np.max(a)

10

In [27]:
np.min(a)

1

#### 1.5. Statistical methods of NumPy arrays:

In [28]:
x=np.arange(1,11)

In [29]:
x.sum()

55

In [30]:
x.mean()

5.5

In [31]:
x.std()

2.8722813232690143

In [32]:
x.var()

8.25

In [33]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [34]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
r= np.arange(1,50,2)
r.reshape((-1,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [62]:
e = r.reshape((5,-1))
e

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [71]:
c = np.array([[2,4,5,8,1]])
c+e

array([[ 3,  7, 10, 15, 10],
       [13, 17, 20, 25, 20],
       [23, 27, 30, 35, 30],
       [33, 37, 40, 45, 40],
       [43, 47, 50, 55, 50]])

In [72]:
z = np.array([[2,4,5,8,1],[2,4,5,8,1],[2,4,5,8,1],[2,4,5,8,1]])
z

array([[2, 4, 5, 8, 1],
       [2, 4, 5, 8, 1],
       [2, 4, 5, 8, 1],
       [2, 4, 5, 8, 1]])

In [73]:
print(z.mean(axis=0))

[2. 4. 5. 8. 1.]


In [64]:
print(e.mean(axis=0))

[21. 23. 25. 27. 29.]


In [35]:
print(y.mean(axis=0))

[4. 5. 6.]


In [36]:
print(y.mean(axis=1))

[2. 5. 8.]


In [37]:
z = np.random.randint(10,size=1000)

In [38]:
z.max()

9

In [39]:
z.min()

0

In [40]:
(z > 5).sum()

392

In [41]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
a = np.array([2,-3,4,5,7,0,1,-1,-34,23])

In [76]:
a.argmax()

9

In [77]:
a.argmin()

8